version: '3.8'

services:
  postgres:
    image: postgres:14.3
    ports:
      - ${DATABASE_PORT}:5432
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    container_name: apidb
    volumes:
      - ./postgres:/var/lib/postgresql/data